export { SimilarSidebar } from "./SidebarShell";
export { CreateProjectModal, DeleteProjectConfirm, SearchResultPopup } from "./modals";
export { SocialPlatformLogo } from "./SocialPlatformLogo";
export {
  // re-export shared helpers used by plugin-path-demo
  getCreatorEmail,
  getCreatorContactEmail,
  getCreatorAveragePlays,
  getCreatorMedianPlays,
  getCreatorCpm,
  getCreatorMedianComments,
  getCreatorMetricSnapshot,
  getCreatorTopicSummary,
  getCreatorReview,
  getCreatorDiagnostics,
  getCreatorLocation,
  getCreatorType,
  getAudienceSummary,
  computeAudienceHighlights,
  getCountryFlag,
  getRegionTierForCountry,
  getRegionTierLabel,
  getSuggestedCpmUsd,
  inferCountryFromLocale,
  parseCpmAmount,
  parseMetricToNumber,
  formatPlays,
  formatLikes,
  formatComments,
  formatFileSize,
  formatScheduleLabel,
  getDefaultScheduleAt,
  getEmailTemplateSegments,
  getEmailTemplateDraft,
  getEmailSubjectSegments,
  getEmailTemplateSubject,
  getCreatorPersonalizationSummary,
  getTagTone,
  getTagChipClasses,
  // constants
  SIDEBAR_CARD_RADIUS,
  SIDEBAR_CONTROL_RADIUS,
  SIDEBAR_COLLAPSED_WIDTH,
  SIDEBAR_MIN_WIDTH,
  SIDEBAR_MAX_WIDTH,
  SIDEBAR_PANEL_CARD_CLASSES,
  SIDEBAR_GRADIENT_CARD_CLASSES,
  SIDEBAR_CONTROL_CLASSES,
  SIDEBAR_SECONDARY_BUTTON_CLASSES,
  SIDEBAR_FILLED_BUTTON_CLASSES,
  SCRAPE_COUNT_OPTIONS,
  HOVER_CARD_MAX_METRICS,
  DEFAULT_HOVER_METRICS,
  DEFAULT_HOVER_METRIC_MODES,
  SOCIAL_PLATFORM_OPTIONS,
  DEFAULT_INLINE_DATA_KEYS,
  DEFAULT_ENABLED_BADGE_CATEGORIES,
  DEFAULT_VIRAL_RATIO_THRESHOLD,
  DEFAULT_FLOP_RATIO_THRESHOLD,
  BADGE_CATEGORY_OPTIONS,
} from "./shared";
